quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/booking_db


quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file


quarkus.http.port=8080

quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n
quarkus.log.level=INFO
quarkus.log.category."io.quarkus".level=INFO
quarkus.log.category."org.hibernate".level=INFO

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

quarkus.smallrye-openapi.path=/openapi
quarkus.smallrye-openapi.info.title=Booking API
quarkus.smallrye-openapi.info.version=1.0.0

quarkus.smallrye-openapi.info.description=API for managing bookings
quarkus.smallrye-openapi.info.contact.name=John Doe