# ===== Database =====
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/booking_db

# Development-only: disable SSL dan GSS untuk koneksi lokal
# quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/booking_db?ssl=false&gssEncMode=disable

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Connection pool
quarkus.datasource.jdbc.max-size=10
quarkus.datasource.jdbc.min-size=2

# ===== HTTP =====
quarkus.http.port=8080

# ===== CORS =====
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=authorization
quarkus.http.cors.access-control-allow-credentials=true

# ===== Logging =====
quarkus.log.level=DEBUG
quarkus.log.category."io.quarkus".level=DEBUG
quarkus.log.category."org.hibernate".level=DEBUG

# ===== JWT =====
smallrye.jwt.verify.key.location=publicKey.pem
smallrye.jwt.verify.key-format=pem-key
mp.jwt.verify.issuer=your-issuer
mp.jwt.verify.claims.principal-claim=upn
# ===== Security =====
quarkus.rest.path=/api/v1

# quarkus.http.auth.permission.default.paths=/api/v1/*
# quarkus.http.auth.permission.default.policy=authenticated
# quarkus.http.auth.permission.default.auth-mechanism=bearer

quarkus.http.auth.permission.public.paths=/api/v1/auth/login,/api/v1/auth/register,/api/v1/auth/refresh,/api/v1/auth/check-email
quarkus.http.auth.permission.public.policy=permit

quarkus.security.jaxrs.deny-unannotated-endpoints=false

quarkus.log.category."io.smallrye.jwt".level=DEBUG
quarkus.log.category."io.quarkus.security".level=DEBUG